version: "3.7"
services: 
  app: 
    build: .
    image: jasonblanchard/jawn-public-client
    command:
      - /bin/bash
      - -c
      - |
        npm start --production
    environment:
      HOMEPAGE_PATH: /workspace
      AUTH_API_PATH: /auth/login
      PORT: 8080
      BASE_PATH: ""
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f app:8080/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - default
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: jasonblanchard/jawn-public-client:test
    command:
      - /bin/bash
      - -c
      - |
        tail -f /dev/null
    environment:
      CYPRESS_BASE_URL: "http://app:8080"
    networks:
      - default
networks:
  default: